// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID        int64
	RoomID    int64
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Room struct {
	ID        int64
	Name      string
	Capacity  int32
	Building  string
	CreatedAt pgtype.Timestamptz
}
