// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Booking struct {
	ID           int64
	RoomID       int64
	UserID       int64
	CreatorRole  string
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	Teacher      pgtype.Text
	GroupNumbers []string
	Subject      pgtype.Text
	LessonType   pgtype.Text
	Week         pgtype.Text
}

type Room struct {
	ID        int64
	Name      string
	Capacity  int32
	Building  string
	CreatedAt pgtype.Timestamptz
}
