// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (room_id, user_id, creator_role, start_time, end_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, room_id, user_id, creator_role, start_time, end_time, teacher, group_numbers, subject, lesson_type, week, created_at
`

type CreateBookingParams struct {
	RoomID      int64
	UserID      int64
	CreatorRole string
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
}

type CreateBookingRow struct {
	ID           int64
	RoomID       int64
	UserID       int64
	CreatorRole  string
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	Teacher      pgtype.Text
	GroupNumbers []string
	Subject      pgtype.Text
	LessonType   pgtype.Text
	Week         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.RoomID,
		arg.UserID,
		arg.CreatorRole,
		arg.StartTime,
		arg.EndTime,
	)
	var i CreateBookingRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.CreatorRole,
		&i.StartTime,
		&i.EndTime,
		&i.Teacher,
		&i.GroupNumbers,
		&i.Subject,
		&i.LessonType,
		&i.Week,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :execrows
DELETE FROM bookings
WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBooking, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, room_id, user_id, creator_role, start_time, end_time, teacher, group_numbers, subject, lesson_type, week, created_at
FROM bookings
WHERE id = $1
`

type GetBookingByIDRow struct {
	ID           int64
	RoomID       int64
	UserID       int64
	CreatorRole  string
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	Teacher      pgtype.Text
	GroupNumbers []string
	Subject      pgtype.Text
	LessonType   pgtype.Text
	Week         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetBookingByID(ctx context.Context, id int64) (GetBookingByIDRow, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i GetBookingByIDRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.CreatorRole,
		&i.StartTime,
		&i.EndTime,
		&i.Teacher,
		&i.GroupNumbers,
		&i.Subject,
		&i.LessonType,
		&i.Week,
		&i.CreatedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, capacity, building, created_at
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Capacity,
		&i.Building,
		&i.CreatedAt,
	)
	return i, err
}

const listBookingsByRoomID = `-- name: ListBookingsByRoomID :many
SELECT id, room_id, user_id, creator_role, start_time, end_time, teacher, group_numbers, subject, lesson_type, week, created_at
FROM bookings
WHERE room_id = $1
ORDER BY start_time, id
`

type ListBookingsByRoomIDRow struct {
	ID           int64
	RoomID       int64
	UserID       int64
	CreatorRole  string
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	Teacher      pgtype.Text
	GroupNumbers []string
	Subject      pgtype.Text
	LessonType   pgtype.Text
	Week         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListBookingsByRoomID(ctx context.Context, roomID int64) ([]ListBookingsByRoomIDRow, error) {
	rows, err := q.db.Query(ctx, listBookingsByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsByRoomIDRow{}
	for rows.Next() {
		var i ListBookingsByRoomIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.CreatorRole,
			&i.StartTime,
			&i.EndTime,
			&i.Teacher,
			&i.GroupNumbers,
			&i.Subject,
			&i.LessonType,
			&i.Week,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUserID = `-- name: ListBookingsByUserID :many
SELECT id, room_id, user_id, creator_role, start_time, end_time, teacher, group_numbers, subject, lesson_type, week, created_at
FROM bookings
WHERE user_id = $1
ORDER BY start_time, id
`

type ListBookingsByUserIDRow struct {
	ID           int64
	RoomID       int64
	UserID       int64
	CreatorRole  string
	StartTime    pgtype.Timestamptz
	EndTime      pgtype.Timestamptz
	Teacher      pgtype.Text
	GroupNumbers []string
	Subject      pgtype.Text
	LessonType   pgtype.Text
	Week         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListBookingsByUserID(ctx context.Context, userID int64) ([]ListBookingsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listBookingsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsByUserIDRow{}
	for rows.Next() {
		var i ListBookingsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.CreatorRole,
			&i.StartTime,
			&i.EndTime,
			&i.Teacher,
			&i.GroupNumbers,
			&i.Subject,
			&i.LessonType,
			&i.Week,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, capacity, building, created_at
FROM rooms
ORDER BY id
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Capacity,
			&i.Building,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
