// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error)
	DeleteBooking(ctx context.Context, id int64) (int64, error)
	GetBookingByID(ctx context.Context, id int64) (GetBookingByIDRow, error)
	GetRoomByID(ctx context.Context, id int64) (Room, error)
	ListBookingsByRoomID(ctx context.Context, roomID int64) ([]ListBookingsByRoomIDRow, error)
	ListBookingsByUserID(ctx context.Context, userID int64) ([]ListBookingsByUserIDRow, error)
	ListRooms(ctx context.Context) ([]Room, error)
}

var _ Querier = (*Queries)(nil)
