// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (room_id, start_time, end_time)
VALUES ($1, $2, $3)
RETURNING id, room_id, start_time, end_time, created_at
`

type CreateBookingParams struct {
	RoomID    int64
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking, arg.RoomID, arg.StartTime, arg.EndTime)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :execrows
DELETE FROM bookings
WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBooking, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, capacity, building, created_at
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Capacity,
		&i.Building,
		&i.CreatedAt,
	)
	return i, err
}

const listBookingsByRoomID = `-- name: ListBookingsByRoomID :many
SELECT id, room_id, start_time, end_time, created_at
FROM bookings
WHERE room_id = $1
ORDER BY start_time, id
`

func (q *Queries) ListBookingsByRoomID(ctx context.Context, roomID int64) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, capacity, building, created_at
FROM rooms
ORDER BY id
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Capacity,
			&i.Building,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
