openapi: 3.1.0
info:
  title: Auth Service API
  version: 1.0.0
  description: API для аутентификации пользователей

paths:
  /auth/register:
    post:
      summary: Регистрация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Пользователь создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Некорректные данные
        '500':
          description: Внутренняя ошибка сервера

  /auth/login:
    post:
      summary: Авторизация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Успешная авторизация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Неверный login или пароль
        '500':
          description: Внутренняя ошибка сервера

components:
  schemas:

    RegisterRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
        role:
          type: string
      required:
        - login
        - password
        - role

    LoginRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
      required:
        - login
        - password

    LoginResponse:
      type: object
      properties:
        token:
          type: string

    UserResponse:
      type: object
      properties:
        id:
          type: integer
        login:
          type: string