version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: timetable_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  parser:
    image: golang:1.25
    profiles: ["parser"]
    working_dir: /app
    env_file:
      - key.env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: go run ./cmd/parser
volumes:
  pg_data:
